
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 09 00:42:28 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int doo = 46;
  public static final int igualigual = 29;
  public static final int allave = 3;
  public static final int cllave = 4;
  public static final int diferenteunario = 28;
  public static final int falsee = 14;
  public static final int switchh = 48;
  public static final int imprimir = 18;
  public static final int mayorq = 30;
  public static final int MASUNARIO = 52;
  public static final int dividir = 24;
  public static final int masmaspost = 42;
  public static final int igual = 2;
  public static final int doublee = 10;
  public static final int intt = 7;
  public static final int elsee = 45;
  public static final int menosmenos = 41;
  public static final int casee = 49;
  public static final int puntoycoma = 6;
  public static final int masmas = 40;
  public static final int menos = 23;
  public static final int iff = 44;
  public static final int truee = 13;
  public static final int EOF = 0;
  public static final int mas = 21;
  public static final int whilee = 37;
  public static final int menorq = 31;
  public static final int error = 1;
  public static final int breakk = 38;
  public static final int entero = 16;
  public static final int por = 22;
  public static final int forr = 47;
  public static final int defaultt = 50;
  public static final int mayorigualq = 33;
  public static final int MENOSUNARIO = 51;
  public static final int dospuntos = 36;
  public static final int stringg = 9;
  public static final int aand = 27;
  public static final int potencia = 25;
  public static final int id = 5;
  public static final int menosmenospost = 43;
  public static final int oor = 26;
  public static final int menorigualq = 32;
  public static final int printLinea = 54;
  public static final int diferente = 34;
  public static final int cpar = 20;
  public static final int booleann = 11;
  public static final int continuee = 39;
  public static final int print = 53;
  public static final int charER = 15;
  public static final int interrogacion = 35;
  public static final int charr = 8;
  public static final int decimal = 17;
  public static final int cadena = 12;
  public static final int apar = 19;
}

