
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 11 17:51:48 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int doo = 49;
  public static final int ccorchete = 8;
  public static final int igualigual = 32;
  public static final int allave = 3;
  public static final int cllave = 4;
  public static final int diferenteunario = 31;
  public static final int falsee = 17;
  public static final int switchh = 51;
  public static final int imprimir = 21;
  public static final int mayorq = 33;
  public static final int MASUNARIO = 55;
  public static final int acorchete = 7;
  public static final int coma = 58;
  public static final int dividir = 27;
  public static final int masmaspost = 45;
  public static final int igual = 2;
  public static final int doublee = 13;
  public static final int intt = 10;
  public static final int write_file = 56;
  public static final int elsee = 48;
  public static final int menosmenos = 44;
  public static final int neww = 9;
  public static final int casee = 52;
  public static final int puntoycoma = 6;
  public static final int masmas = 43;
  public static final int finall = 64;
  public static final int protegido = 61;
  public static final int menos = 26;
  public static final int iff = 47;
  public static final int truee = 16;
  public static final int EOF = 0;
  public static final int estatico = 63;
  public static final int mas = 24;
  public static final int whilee = 40;
  public static final int menorq = 34;
  public static final int publico = 60;
  public static final int error = 1;
  public static final int breakk = 41;
  public static final int entero = 19;
  public static final int por = 25;
  public static final int forr = 50;
  public static final int defaultt = 53;
  public static final int mayorigualq = 36;
  public static final int MENOSUNARIO = 54;
  public static final int dospuntos = 39;
  public static final int stringg = 12;
  public static final int aand = 30;
  public static final int potencia = 28;
  public static final int id = 5;
  public static final int menosmenospost = 46;
  public static final int oor = 29;
  public static final int read_file = 57;
  public static final int privado = 62;
  public static final int menorigualq = 35;
  public static final int printLinea = 66;
  public static final int diferente = 37;
  public static final int cpar = 23;
  public static final int booleann = 14;
  public static final int continuee = 42;
  public static final int print = 65;
  public static final int charER = 18;
  public static final int grafica = 59;
  public static final int interrogacion = 38;
  public static final int charr = 11;
  public static final int decimal = 20;
  public static final int cadena = 15;
  public static final int apar = 22;
}

