
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 05 17:24:08 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayorq = 24;
  public static final int menorigualq = 26;
  public static final int diferenteunario = 22;
  public static final int decimal = 8;
  public static final int allave = 3;
  public static final int imprimir = 12;
  public static final int cpar = 14;
  public static final int por = 16;
  public static final int aand = 21;
  public static final int menos = 17;
  public static final int cllave = 4;
  public static final int charER = 6;
  public static final int intt = 10;
  public static final int MENOSUNARIO = 29;
  public static final int igual = 2;
  public static final int EOF = 0;
  public static final int charr = 11;
  public static final int id = 5;
  public static final int potencia = 19;
  public static final int error = 1;
  public static final int mayorigualq = 27;
  public static final int oor = 20;
  public static final int entero = 7;
  public static final int diferente = 28;
  public static final int menorq = 25;
  public static final int mas = 15;
  public static final int igualigual = 23;
  public static final int puntoycoma = 9;
  public static final int dividir = 18;
  public static final int apar = 13;
}

